[package]
name = "serve"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.8.4"
log = "0.4.14"
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "1.7.1", features = ["full"] }
